class TestData:
    CHROME_executable_path = "C:/Users/fayeche/PycharmProjects/pyTest/driver/chromedriver.exe"
    base_url = "https://www.talan-academy.com"
    nom = "Ayeche"
    prenom = "Fares"
    email = "fares.ayeche@talan.com"
    mdp = "Fares1993"
    cmdp = "Fares1993"
    url_page_login = "https://www.talan-academy.com/#login"
    b = "https://www.talan-academy.com"
    emailNV = "fares.ayec@talan.com"
    mdpNV = "Fares199"
    url_page_dashboard = "https://www.talan-academy.com/apprenti/dashboard"
    """data of test change tel number"""
    telValid = "99101697"
    telNonValid = "0000000000000000"